from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView

from .views import (
    RegisterView, PatientViewSet, DoctorViewSet, 
    MappingListCreateView, MappingDetailView
)

router = DefaultRouter()
router.register(r'patients', PatientViewSet, basename='patient')
router.register(r'doctors', DoctorViewSet, basename='doctor')

urlpatterns = [
    # 1. Auth APIs
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', TokenObtainPairView.as_view(), name='login'),
    
    # 2 & 3. Patient and Doctor APIs (Generated by Router)
    path('', include(router.urls)),
    
    # 4. Mapping APIs
    path('mappings/', MappingListCreateView.as_view(), name='mapping-list-create'),
    
    # Handles GET /api/mappings// and DELETE /api/mappings//
    path('mappings//', MappingDetailView.as_view(), name='mapping-detail'),
]